### ISSUE TITLE
Minor Suggestions

### ISSUE THREAD

**Issue by peterdtitan** [ishpaul777/Awesome-Books#4]
Great work so far 👏 👏 👏 

No current issues were found with your work and I must say quite outstanding.
Just a minor suggestion though: 

- [ ] Try not to push commented blocks of codes to your main repo. 

https://github.com/ishpaul777/Awesome-Books/blob/1a4adc640fcc394317576ab7e4e06fc674ec043d/js/app.js#L186
https://github.com/ishpaul777/Awesome-Books/blob/1a4adc640fcc394317576ab7e4e06fc674ec043d/js/app.js#L187
https://github.com/ishpaul777/Awesome-Books/blob/1a4adc640fcc394317576ab7e4e06fc674ec043d/js/app.js#L188
https://github.com/ishpaul777/Awesome-Books/blob/1a4adc640fcc394317576ab7e4e06fc674ec043d/js/app.js#L189
https://github.com/ishpaul777/Awesome-Books/blob/1a4adc640fcc394317576ab7e4e06fc674ec043d/js/app.js#L190
https://github.com/ishpaul777/Awesome-Books/blob/1a4adc640fcc394317576ab7e4e06fc674ec043d/js/app.js#L191

This gives your work a bit of an unprofessional feel. What you could do instead: 

-  Make notes in a different branch for changes you want to implement later on.
-  Save changes somewhere else locally.

**Comment by stephnna** [comment]
Good work
